application: xelayacumen
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|pdf|eot|svg|ttf|woff))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|pdf|eot|svg|ttf|woff))
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /.*
  script: xelay.app
